name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 2.1.1
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:  
  analyzer: ^1.1.0
  build: ^1.6.3
  build_config: ^0.4.6
  code_builder: ^3.6.0
  dart_style: ^1.3.14
  kiwi: ^2.1.1
  path: ^1.8.0
  source_gen: ^0.9.10+3
  built_collection: ^5.0.0

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  test: ^1.16.5
