name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 3.0.0-nullsafety-generator.3
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  # Keeping this <2.12.0 because the code is not null safe – yet!
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  build_config: ^0.4.7
  code_builder: ^3.7.0
  dart_style: ^2.0.0
  kiwi: ^3.0.0-nullsafety.0
  path: ^1.8.0
  source_gen: ^1.0.0
  built_collection: ^5.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  test: ^1.16.8

dependency_overrides:
  kiwi:
    path: ../kiwi