name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 0.5.2
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:  
  analyzer: ^0.39.10
  build: ^1.3.0
  build_config: ^0.4.2
  code_builder: ^3.3.0
  dart_style: ^1.3.6
#  kiwi: ^1.0.0
  kiwi:
    path: ../kiwi
  path: ^1.6.4
  source_gen: ^0.9.5

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^1.2.0
  test: ^1.14.7
