name: kiwi_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: romai <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:  
  source_gen: any
  code_builder: ^3.1.3
  build_config: ^0.3.1+2
  kiwi:
    path:
      ../kiwi

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.3+1
