name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 0.1.1
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:  
  analyzer: ^0.32.2
  build: ^0.12.6
  path: ^1.3.2
  dart_style: ^1.0.0
  source_gen: ^0.9.0+1
  code_builder: ^3.1.3
  build_config: ^0.3.1+2
  kiwi: '>=0.1.0 <0.2.0'

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.3+1
  build_runner: ^0.10.1
