name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 3.0.1
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  build_config: ^1.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  kiwi: ^3.0.0
  path: ^1.8.0
  source_gen: ^1.0.1
  built_collection: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.1.0
  test: ^1.17.5

dependency_overrides:
  kiwi:
    path: ../kiwi